name:                eco
version:             0.1.0.0
homepage:            https://github.com/silky/ecological-climatology#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonvandersilk@gmail.com
copyright:           2022 Noon van der Silk
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - units
  - units-defs
  - asciichart
  - ansigraph

executables:
  eco:
    source-dirs:      src
    main:             Main.hs
